name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy-to-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Build
        run: docker build -t stalker .
      - name: Create Tag
        run: docker tag stalker oncom/stalker:1.0.0
      - name: Push
        run: docker push oncom/stalker:1.0.0